name: weigang-tian-tian-ding-sign-in

on:
  workflow_dispatch:
  schedule:
    # “At minute 0.” https://crontab.guru/#0_*_*_*_*
    - cron: "0 * * * *"
env:
  WEIGANG_TIAN_TIAN_DING_ACCESS_TOKEN: ${{ secrets.WEIGANG_TIAN_TIAN_DING_ACCESS_TOKEN }}

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: |
          node ./weigang-tian-tian-ding-sign-in.mjs


